---
title: "Scan Raw Data"
output:
#  bookdown::pdf_document2:
#    toc: TRUE
  bookdown::html_document2: 
    toc: TRUE
    toc_float: TRUE
    theme: cosmo
link-citations: yes
fontsize: 12pt
editor_options: 
  markdown: 
    wrap: sentence
---

**FastQC**

FastQC is a program that will scan raw genomic data and identify if adapters or low quality reads are present. For more information, or to download, visit [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/).

 To run FastQC on your raw genomic data (fastq file), be sure that FastQC module is available and loaded on your HPC, and write a job script using the following code:
 
 ```Bash
 echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
 #fastqc command
 fastqc <FILE.fastq>
#
 echo = `date` job $JOB_NAME done
 ```
 Once the job is complete, access the results and images. There are multiple ways to share files, including the following:

**ffsend**

Ffsend allows you to easily and securely share files from the command line by generating a temporary URL for you to download to your device, or share with others. For more or to download, visit [ffsend](https://github.com/timvisee/ffsend). 
 
 ```Bash
 #load module on your HPC
 module load ffsend
#
 #command to generate a temporary URL
 ffsend upload <file>
 ```
**secure copy**

 The secure copy command allows you to copy files between servers securely. You can copy files from your personal machine to your HPC, your HPC to your personal machine, or between users on your HPC server.
 
 ```Bash
 #secure copy command
 scp <user:/current/path/to/file> <user:/location/where/you/would/like/to/move/file/to>
#
 #alternatively, if you are in the directory or location of where you want to move your file to within your window, you can also code the following, where "./" means "move here":
 scp <user:/current/path/to/file> ./ 
```



