---
title: "Unix/Linux Cheat Sheet"
output:
#  bookdown::pdf_document2:
#    toc: TRUE
  bookdown::html_document2: 
    toc: TRUE
    toc_float: TRUE
    theme: cosmo
link-citations: yes
fontsize: 12pt
editor_options: 
  markdown: 
    wrap: sentence
---
**wget** - stands for web get, allows you to download files from the web

**ls** - list contents of directory

**ls -ltr** - list items in directory and show in "long format" to list permissions, size, and modification date

**ls -hl** - list all items in long, "human readable" format

**history** - print history of commands submitted

**less** - to show a file's content one screen at a time, compared to showing all contents

**head** - will show top 10 lines of file

**tail** - will show last 10 lines of file

**tail -#** - will show last # lines of file

**tail -f file** - show output the contents of file as it grows, starting with the last 10 lines

**cd** - change directory

**cd..** - change directory "up one", increased by the number of .'s following

**cd /** - change to the root directory

**cd ~** - change to to your home directory

**cd -** - change to the last directory you were just in

**pwd** - print working directory, shows current path of directory

**realpath file** - shows path for file

**mkdir** - make new directory

**rm()** - remove, deletes file or directory

**cp file1 file2** - copy file1 to file2

**scp <user:/current/path/to/file> <user:/location/where/you/would/like/to/move/file/to>** - secure copy from one location to another

**mv file1 file2** - move (rename) file1 to file2

**mv file1 ~/file1** - move file1 from the current directory to user’s home directory

**cat()** - show output contents of a file or job log

**nano** - open nano, text editor

**nano file** - open file using nano text editor

**q** - quit interface

**clear** - clear terminal screen

**man** - print manual

**module avail** - check which modules are available on your HPC

**qstat** - check out stats on a job

**exit** - exit terminal session
